### ISSUE TITLE
Hope I can Learn from you

### ISSUE THREAD

**Issue by congzhangzh** [damikun/trouble-training#3]
Hi friend,

Which tools you use to draw these so beautiful architecture diagrams?

Tks,
Cong

**Comment by damikun** [comment]
Hi @congzhangzh please use GitHub discussions for this kind of questions... (It on main tab)

**To your question:**  I used no tools for this just plain vector or chart editor... You need to build it from scratch..

**Comment by congzhangzh** [comment]
Tks:)
